Feature/calc v3.0(add new operation)
melanu1991/Task3 pull request #12
Opened 2017-07-16 10:28 UTC by melanu1991

2017-07-18 21:50 UTC, imironenko requested changes

2017-07-18 21:50 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +- (ExecuteOperation )returnSelectedExecuteBlockWithName:(NSString *)name {
не стоит использовать `return` префикс
лучше будет, напр. `operationForType:`

2017-07-18 21:50 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +    [self.calcModel addOperation:operation withExecuteBlock:[self returnSelectedExecuteBlockWithName:operation]];
что будет если операция уже добавлена ?

2017-07-19 09:36 UTC, melanu1991 commented on Calculator/Calculator/ViewController.m
> +    [self.calcModel addOperation:operation withExecuteBlock:[self returnSelectedExecuteBlockWithName:operation]];
Вообще будет перезаписана, но так как у меня в методе addOperation стоит проверка, ничего не произойдет если операция была, если не было тогда добавится. 
NSArray *allOperation = [self.arrayOfOperation allKeys];
    if (![allOperation containsObject:operation]) {
        self.arrayOfOperation[operation] = executeBlock;
    }

2017-07-25 21:33 UTC, imironenko approved these changes
👍

2017-07-27 11:36 UTC, merged