Feature/calc3.0
melanu1991/Task3 pull request #6
Opened 2017-05-31 16:27 UTC by melanu1991

2017-06-02 23:08 UTC, imironenko requested changes

2017-06-02 23:08 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.h
> +@property (nonatomic, assign, getter=isNextOperand) BOOL NextOperand;
Не верное наименование, используем lowerCase

2017-06-02 23:08 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +    for (UIButton *button in self.binButtons) {
Давай использовать KVC, `[self.binButtons setValue:@YES forKey:@"enabled"];`
Аналогично для всех коллекций

2017-06-02 23:08 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +@property (nonatomic, strong) BinarySystem *binarySystem;
Давай перенесем логику систем счисления в модель

2017-06-02 23:08 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +@property (nonatomic, assign, getter=isEqualButtonPressed) BOOL equalButtonPressed;
Давай попробуем избавиться от использование данного флага в контроллере

2017-06-02 23:08 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +@property (nonatomic, assign, getter=isDotButton) BOOL dotButton;
Мы можем упростить логику контроллера и не использовать данный флаг ?

2017-06-02 23:08 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +@property (nonatomic, assign,getter=isDec) BOOL dec;
После переноса систем счисления в модель, необходимость в данном флаге должна отпасть

2017-06-05 20:01 UTC, imironenko requested changes

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/BinarySystem.m
> +    if ([sign isEqualToString:@"-"]) {
Давай "-" вынесем в константу

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/BinarySystem.m
> +        return @"0";
Давай сделаем константу для "0"

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/BinarySystem.m
> +    if ([sign isEqualToString:@"-"]) {
Давай использовать константу для "-", где возможно

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.m
> +        _binSystem = [[[BinarySystem alloc]init]retain];
memory leak

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.m
> +        _octSystem = [[[OctSystem alloc]init]retain];
memory leak

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.m
> +        _currentNumberSystem = [@"DEC" retain];
Давай использовать константу для "DEC"

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.m
> +    if ([self.currentNumberSystem isEqualToString:@"DEC"]) {
Стоит использовать константы для  систем счисления "DEC", "BIN", "OCT", "HEX"

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.m
> +- (void)changeNumberSystemWithNewSystem:(NSString *)newNumberSystem withCurrentValue:(NSString *)currentValue {
нет надобности использовать префикс "with" для второго параметра

2017-06-05 20:01 UTC, imironenko commented on Calculator/Calculator/CalculatorModel.m
> +    if ([newNumberSystem isEqualToString:@"BIN"]) {
эти вычисления корректны, они замещают предыдущие конвертирование ?

2017-06-07 08:16 UTC, imironenko requested changes

2017-06-07 08:16 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +        if (i < count) {
условия можно использовать как флаг, напр `[button setEnabled:(i < count)];`
таким образом убрать if

2017-06-07 08:16 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +    int count = 0, i = 0;
наименование `count` не несет смысловой нагрузки, лучше подойдет `notationSystem` либо что то в этом духе

2017-06-07 08:16 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +        i++;
мы не используем while цикл, если надо аргумент, правильнее написать обычный цикл `for (i = 0; i < self.buttons.count; i++) {...}`

2017-06-07 08:16 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +    for (UIButton *button in self.buttons) {
перебор по `self.buttons` гуд, но одно но, в какой последовательности ты добавлял outlet в коллекцию, в такой последовательности они и упорядочены, захочешь изменить придется передобовлять :)
И, я так понимаю, self.buttons - это digit buttons ? в таком случае, стоит более осмысленней именовать

2017-06-07 08:16 UTC, imironenko commented on Calculator/Calculator/ViewController.m
> +- (IBAction)BinOctDecHexSystemPressedButton:(UIButton *)sender {
переименуй метод на более осмысленней

2017-06-07 08:42 UTC, melanu1991 commented on Calculator/Calculator/ViewController.m
> +    for (UIButton *button in self.buttons) {
Да я уже понял насчет упорядоченности+)

2017-06-09 14:22 UTC, imironenko approved these changes
👍

2017-07-10 13:09 UTC, merged